name: solh
description: Solh App by OMLogic


version: 1.0.33+76


environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  firebase: ^9.0.2
  firebase_core: ^2.13.1
  sizer: ^2.0.15
  smooth_page_indicator: ^1.0.0+2
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.6 
  firebase_auth: ^4.6.2
  country_code_picker: ^3.0.0
  pin_code_fields: ^7.4.0
  image_picker: ^0.8.5
  image_cropper: ^4.0.1
  cached_network_image: ^3.2.0
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  pull_to_refresh: ^2.0.0
  url_launcher: ^6.1.0
  intl: ^0.18.1
  timeago: ^3.2.2
  get: ^4.6.1
  fluttertoast: ^8.0.9
  readmore: ^2.1.0
  video_trimmer: ^2.1.0
  video_player: ^2.4.0
  flutter_native_splash: ^2.1.6
  shimmer: ^3.0.0
  firebase_messaging: ^14.6.2
  pie_chart: ^5.3.1
  dotted_border: ^2.0.0+2
  socket_io_client: ^2.0.0
  webview_flutter: ^4.2.2
  flutter_html: ^3.0.0-alpha.5
  agora_rtc_engine: ^6.2.0
  permission_handler: ^10.0.0
  file_picker: ^5.0.1
  open_filex: ^4.1.0
  firebase_analytics: ^10.4.2
  upgrader: ^6.5.0
  firebase_dynamic_links: ^5.3.2
  youtube_player_iframe: ^4.0.4
  onesignal_flutter: ^3.4.2
  proste_indexed_stack: ^0.2.4
  facebook_app_events: ^0.19.0
  carousel_slider: ^4.2.1
  html: ^0.15.1
  flutter_stripe: ^9.2.1
  cache_manager: ^1.0.0+4
  connectivity_plus: ^4.0.1
  flutter_speed_dial: ^7.0.0
  wakelock: ^0.6.2
  flutter_dotenv: ^5.1.0
  feature_discovery: ^0.14.1
  share_plus: ^6.3.4

  #alt_sms_autofill: ^1.0.0

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
dependency_overrides:
  firebase_core_platform_interface: 4.8.0
flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/app-bar/
    - assets/icons/profile/
    - assets/icons/profile-setup/
    - assets/icons/journaling/
    - assets/icons/bottom-navigation-bar/
    - assets/images/logo/
    - assets/images/
    - assets/images/get_help/
    - assets/icons/group/
    - assets/intro/png/
    - .env

