name: solh
description: Solh App by OMLogic

version: 1.0.5+50

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  firebase: ^9.0.2
  firebase_core: ^1.16.0
  auto_route: ^3.2.4
  sizer: ^2.0.15
  smooth_page_indicator: ^1.0.0+2
  google_fonts: 2.3.2
  flutter_svg: ^1.0.3 
  firebase_auth: ^3.3.16
  country_code_picker: ^2.0.2
  pin_code_fields: ^7.4.0
  image_picker: ^0.8.5
  image_cropper: ^2.0.0
  cached_network_image: ^3.2.0
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  pull_to_refresh: ^2.0.0
  url_launcher: ^6.1.0
  intl: ^0.17.0
  timeago: ^3.2.2
  get: ^4.6.1
  fluttertoast: ^8.0.9
  readmore: ^2.1.0
  video_trimmer: ^1.1.3
  video_player: ^2.4.0
  new_version: ^0.3.0
  flutter_native_splash: ^2.1.6
  shimmer: ^2.0.0
  firebase_messaging: ^11.4.2
  lottie: ^1.3.0
  swipe_deck: ^1.1.0
  carousel_slider: ^4.1.1
  pie_chart: ^5.3.1
  dotted_border: ^2.0.0+2
  socket_io_client: ^2.0.0

  webview_flutter: ^3.0.4
  flutter_local_notifications: ^9.7.0
  
  awesome_notifications: ^0.6.21
  flutter_html: ^3.0.0-alpha.5
  agora_rtc_engine: ^5.3.0
  permission_handler: ^10.0.0
  onesignal_flutter: ^3.4.1
  file_picker: ^5.0.1

  #alt_sms_autofill: ^1.0.0

dev_dependencies:
  build_runner:
  auto_route_generator: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/app-bar/
    - assets/icons/profile/
    - assets/icons/profile-setup/
    - assets/icons/journaling/
    - assets/icons/bottom-navigation-bar/
    - assets/icons/comment-screen/
    - assets/images/logo/
    - assets/images/
    - assets/icons/group/
    - assets/images/journal-demo/
    - assets/icons/consultants/
    - assets/intro/png/

