name: solh
description: Solh App by OMLogic

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  firebase: ^9.0.2
  firebase_core: ^1.8.0
  auto_route: 3.0.3
  sizer: ^2.0.15
  smooth_page_indicator: ^1.0.0+2
  google_fonts: ^2.1.0
  flutter_svg: ^0.23.0+1
  firebase_auth: ^3.1.4
  country_code_picker: ^2.0.2
  pin_code_fields: ^7.3.0
  flutter_staggered_grid_view: ^0.4.1
  image_picker: ^0.8.4+3
  image_cropper: ^1.4.1
  cached_network_image: ^3.1.0
  flutter_slider_drawer: ^2.0.0
  hive: ^2.0.4
  provider: ^6.0.1
  date_time_picker: ^2.1.0
  shared_preferences: ^2.0.9
  pull_to_refresh: ^2.0.0
  url_launcher: ^6.0.17
  intl: ^0.17.0
  timeago: ^3.1.0


dev_dependencies:
  build_runner:
  auto_route_generator: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/app-bar/
    - assets/icons/profile/
    - assets/icons/profile-setup/
    - assets/icons/journaling/
    - assets/icons/bottom-navigation-bar/
    - assets/icons/comment-screen/
    - assets/images/logo/
    - assets/images/journal-demo/
    - assets/icons/consultants/
    - assets/intro/png/

