import 'package:get/instance_manager.dart';
import 'package:solh/features/lms/display/course_home/data/repo/course_banner_repo_impl.dart';
import 'package:solh/features/lms/display/course_home/data/repo/course_cat_repo_impl.dart';
import 'package:solh/features/lms/display/course_home/data/repo/featured_course_repo_impl.dart';
import 'package:solh/features/lms/display/course_home/domain/repo/course_banner_repo.dart';
import 'package:solh/features/lms/display/course_home/domain/repo/course_cat_repo.dart';
import 'package:solh/features/lms/display/course_home/domain/repo/featured_course_repo.dart';
import 'package:solh/features/lms/display/course_home/domain/usecases/course_banner_usecase.dart';
import 'package:solh/features/lms/display/course_home/domain/usecases/course_cat_usecase.dart';
import 'package:solh/features/lms/display/course_home/domain/usecases/featured_course_usecase.dart';
import 'package:solh/features/lms/display/course_home/ui/controllers/course_banner_controller.dart';
import 'package:solh/features/lms/display/course_home/ui/controllers/course_cat_controller.dart';
import 'package:solh/features/lms/display/course_home/ui/controllers/feature_course_controller.dart';
import 'package:solh/features/lms/display/course_listing/data/repo/course_list_repo_impl.dart';
import 'package:solh/features/lms/display/course_listing/domain/repo/course_list_repo.dart';
import 'package:solh/features/lms/display/course_listing/domain/usecases/course_list_usecase.dart';
import 'package:solh/features/lms/display/course_listing/ui/controllers/course_list_controller.dart';

part 'course_di_setup.dart';
