import 'package:get/get.dart';
import 'package:solh/ui/screens/products/features/home/data/repo/product_category_repo_impl.dart';
import 'package:solh/ui/screens/products/features/home/data/repo/product_mainCat_repo_impl.dart';
import 'package:solh/ui/screens/products/features/home/domain/repo/product_category_repo.dart';
import 'package:solh/ui/screens/products/features/home/domain/repo/product_mainCat_repo.dart';
import 'package:solh/ui/screens/products/features/home/domain/usecases/product_mainCat_usecase.dart';
import 'package:solh/ui/screens/products/features/home/domain/usecases/products_category_usecase.dart';
import 'package:solh/ui/screens/products/features/home/ui/controllers/product_category_controller.dart';
import 'package:solh/ui/screens/products/features/home/ui/controllers/product_mainCat_controller.dart';
import 'package:solh/ui/screens/products/features/product_detail/data/repo/product_detail_repo_impl.dart';
import 'package:solh/ui/screens/products/features/product_detail/domain/repo/product_detail_repo.dart';
import 'package:solh/ui/screens/products/features/product_detail/domain/usecases/product_detail_usecase.dart';
import 'package:solh/ui/screens/products/features/product_detail/ui/controller/product_detail_controller.dart';
import 'package:solh/ui/screens/products/features/products_list/data/repo/product_list_repo_impl.dart';
import 'package:solh/ui/screens/products/features/products_list/domain/repo/product_list_repo.dart';
import 'package:solh/ui/screens/products/features/products_list/domain/usecases/product_list_usecase.dart';
import 'package:solh/ui/screens/products/features/products_list/ui/controllers/products_list_controller.dart';

part 'products_di_setup.dart';
