import 'package:get/get_navigation/src/root/internacionalization.dart';

class Languages extends Translations {
  @override
  // TODO: implement keys
  @override
  Map<String, Map<String, String>> get keys => {
        "hi_IN": {
          "Do you really want to exit app?":
              "क्या आप वाकई ऐप से बाहर निकलना चाहते हैं?",
          "Yes": "हाँ",
          "No": "नहीं",
          "ERROR": "एरर",
          "TRY AGAIN": "पुनः प्रयास करें",
          "Not found": "नहीं मिला",
          "Find help": "सहायता प्राप्त करें",
          "Reject": "अस्वीकार करें",
          "Trending Posts": "ट्रेंडिंग",
          "Accept": "स्वीकार करें",
          "Other Detail": "अन्य जानकारी",
          "My Diary": "माय डायरी",
          "Post Publically": "सार्वजनिक रूप से पोस्ट करें",
          "Close": "बंद करें",
          "Diary Entries": "डायरी एंट्रीज़",
          "Issues, Organisation": "समस्याएँ, संगठन ",
          "Well, there's nothing here! Why don't you begin today?":
              "खैर, यहाँ कुछ नहीं है! आप आज ही क्यों नहीं शुरू करते?",
          "Psychological Capital": "मनोवैज्ञानिक कैपिटल",
          "Your Capital": "आपकी कैपिटल",
          "Your Psychological Capital": "आपकी मनोवैज्ञानिक कैपिटल",
          "This is a grand total based on your Engagement on the app":
              "यह ऐप पर आपके जुड़ाव के आधार पर मनोवैज्ञानिक पूंजी का कुल जोड़ है",
          "Badges up Next": "अगला बैज",
          "Earn more psychological capital for respective badge & make it yours":
              "संबंधित बैज के लिए अधिक मनोवैज्ञानिक पूंजी कमाएं और इसे अपना बनाएं",
          "Typing....": "टाइपिंग....",
          "Please wait a moment while we connect you to one of our Solh certified professionals.":
              "कृपया प्रतीक्षा करें, आपको जल्द Solh के एक्सपर्ट् के साथ जोड़ा जा रहा है",
          "Please take this conversation further. The seeker is waiting for you.":
              "कृपया इस बातचीत को आगे बढ़ाएं। आपकी प्रतीक्षा की जा रही है। ",
          "Rate your Experience": "अपने अनुभव को रेट करें",
          "Your chat ended, Please rate your experience":
              "आपकी चैट समाप्त हो गई, कृपया अपने अनुभव को रेट करें",
          "Skip": "छोड़ें",
          "Please write your feedback here":
              "कृपया अपनी प्रतिक्रिया यहाँ लिखें",
          "Submit": "जमा करें",
          "Groups For You": "आपके लिए समूह",
          "Do you really want to end the chat?":
              "क्या आप वाक़ई चैट समाप्त करना चाहते हैं?",
          "Cancel": "रद्द करें",
          "Leave": "जाने दें",
          "Comments": "टिप्पणियाँ",
          "You can not see this user": "आप इस यूजर को नहीं देख सकते",
          "Best": "सर्वश्रेष्ठ",
          "My Profile": "माय प्रोफाइल",
          "Replies": "जवाब",
          "Likes": "लाइक्स",
          "Feeling": "भावना",
          "Go To Group": "समूह में जाएं",
          "join": "जुड़ें",
          "Connect": "जुडिये",
          "Connections": "संबंध",
          "Message": "संदेश भेजें",
          "Connect": "जुडिये",
          "Posts": "पोस्ट",
          "Capital": "कैपिटल",
          "Unfriend": "मित्रता समाप्त करें",
          "Cancle": "रद्द करें",
          "Sessions & Packages": "सेशन और पैकेज",
          "Report this person": "इस व्यक्ति की रिपोर्ट करें",
          "Wheel of Emotions": "भावनाओं का चक्र",
          "Activity Log": "एक्टिविटी लॉग",
          "Block this person": "इस व्यक्ति को ब्लॉक करें",
          "Person Successfully Blocked": "व्यक्ति को ब्लॉक कर दिया गया है",
          "Oops !! Something Went Wrong": "Oops!! कुछ गलत हो गया है",
          "Successfully Reported User": "व्यक्ति को रिपोर्ट कर दिया गया है",
          "Online": "ऑनलाइन",
          "Offline": "ऑफलाइन",
          "Completed": "पूरा हो चुका है",
          "No Scheduled Appointment yet": "अभी तक कोई अपॉइंटमेंट नहीं है",
          "Session": "सेशन",
          "Not Available Now": "अभी उपलब्ध नहीं है",
          "Booking Online Session": "ऑनलाइन सेशन की बुकिंग",
          "Confirm": "पुष्टि करें",
          "Thank You": "धन्यवाद",
          "Your appointment has been successfully booked on":
              "आपका अपॉइंटमेंट सफलतापूर्वक बुक कर लिया गया है",
          "No Package": "कोई पैकेज नहीं है",
          "Total Payable": "कुल भुगतान योग्य",
          "Buy Plan": "योजना खरीदें",
          "Continue": "जारी रखें",
          "Years": "साल",
          "About": "विषय",
          "Select Pack": "पैक चुनें",
          "Hide": "छिपाएं",
          "View": "देखें",
          "Tax Incl.": "कर सहित",
          "Change": "बदलें",
          "Book Now & Pay Later": "अभी बुक करें और बाद में भुगतान करें",
          "Billing Details": "बिल डिटेल्स",
          "Consultaion Fee": "परामर्श शुल्क",
          "By confirming you agree": "अपनी उम्र की पुष्टि करके",
          "Terms & Conditions": "नियम और शर्तें",
          "Solh Promises": "Solh के वादे",
          "Complete anonymity": "पूर्ण गुमनामी",
          "A safe space with no judgement": "बिना निर्णय के एक सुरक्षित स्थान",
          "The best doctors and therapists": "सबसे अच्छे डॉक्टर और चिकित्सक",
          "Round the clock support": "24 घंटे समर्थन",
          "Details": "विवरण",
          "Paid": "भुगतान किया गया",
          "Consultation Fee": "परामर्श शुल्क",
          "Book Appointment": "भुगतान किया गया",
          "Starting @": "शुरुआत",
          "Show More": "और दिखाए",
          "Show less": "कम दिखाएं",
          "No Consultant available for your country":
              "आपके देश के लिए कोई सलाहकार उपलब्ध नहीं है",
          "No Doctors Found": "डॉक्टर उपलब्ध नहीं है",
          "View All": "सब देखें",
          "Request Sent": "अनुरोध भेजा गया",
          "Email-id": "Email-ID  ",
          "Benefits": "फ़ायदे",
          "No results found": "कोई परिणाम नहीं मिला",
          "Filter counsellors": "फ़िल्टर सलाहकार",
          "Country": "देश",
          "Clinician": "चिकित्सक",
          "Allied Therapy": "अलाइड थेरेपी",
          "years": "साल",
          "Preview": "समीक्षा",
          "Consultants": "सलाहकार",
          "Name, age, gender": "नाम, उम्र, लिंग",
          "Issues": "समस्याएँ",
          "Speciality": "विशेषता",
          "Clear all": "सब साफ़ करें",
          "Apply": "लागू करें",
          "Allied Therapies": "अलाइड थेरेपी",
          "Featured Therapists": "विशेष चिकित्सक",
          "Therepist Name": "चिकित्सक का नाम",
          "Profession": "पेशा",
          "Consultations": "विचार-विमर्श",
          "Rating": "रेटिंग",
          "Recorded": "दर्ज किया गया",
          "Live packages": "लाइव पैकेज",
          "Popular Packages": "लोकप्रिय पैकेज",
          "Solh Mates": "Solh Mates",
          "Today": "आज",
          "Search for Support": "समर्थन खोजें",
          "Search by Profession": "पेशे से खोजें",
          "Search for People, consultants, Posts or groups ...":
              "लोग, सलाहकार, पोस्ट या समूह खोजें ...",
          "No Result Found": "कोई परिणाम नहीं मिला",
          "Edit Group Details": "ग्रुप डिटेल्स एडिट करें",
          "Create Group": "ग्रुप बनायें",
          "Public": "सार्वजनिक",
          "Save": "सेव",
          "Next": "अगला",
          "posts": "पोस्ट",
          "Group Description": "ग्रुप विवरण",
          "Join Group": "ग्रुपमें शामिल हों",
          "Post in group": "ग्रुप में पोस्ट करें",
          "See Post": "पोस्ट देखें",
          "Members": "सदस्य",
          "Admin": "एडमिन",
          "Edit": "एडिट",
          "Delete": "मिटाए",
          "Exit group": "ग्रुप छोड़ें",
          "Do You want to Exit group ?":
              "क्या आप ग्रुप से बाहर निकलना चाहते हैं?",
          "Yes": "हाँ",
          "Join As": "के रूप में जुड़ें",
          "Join": "जुड़ें",
          "Invite Members": "सदस्यों को आमंत्रित करें",
          "Send Invite": "निमंत्रण भेजें",
          "Groups": "ग्रुप्स",
          "Home": "होम",
          "Joined": "जुड़ गए",
          "No groups joined yet": "अभी तक किसी ग्रुप से नहीं जुड़े हैं ",
          "new suggestions are on the way": "नए सुझाव आ रहे हैं",
          "Blog Details": "ब्लॉग विवरण",
          "Journaling": "जर्नलिंग",
          "Goal Setting": "लक्ष्य निर्धारण",
          "Add Goals +": "लक्ष्य जोड़ें",
          "Add Goal": "लक्ष्य जोड़ें",
          "I want to work on": "मैं काम करना चाहता हूँ",
          "Self Assessments": "आत्म मूल्यांकन",
          "Get Help": "मदद प्राप्त करें",
          "Take the first step": "पहला कदम उठाएं",
          "Anonymous": "गुमनाम",
          "Anxiety": "चिंता",
          "Overwhelmed with emotions: Talk to a Solh counsellor NOW":
              "भावनाओं से अभिभूत: अभी Solh सलहाकार से बात करें",
          "Start chatting for free right away, with a Solh Counselor.":
              "Solh एक्सपर्ट्स से मुफ्त में बात करें",
          "Allied Experts": "अलाइड एक्सपर्ट्स",
          "You will be connected to solh counsellor":
              "आप Solh काउंसलर से जुड़े रहेंगे",
          "Talk Now": "अभी बात करें",
          "DISCLAMER": "उद् घोषणा",
          "We are not a medical emergency or suicide prevention service . If you are feeling suicidal, please.":
              "हम कोई मेडिकल इमरजेंसी या आत्महत्या रोकथाम सेवा नहीं हैं। यदि आप आत्महत्या का विचार कर रहे हैं, तो कृपया राष्ट्रीय आत्महत्या रोकथाम लाइफ़लाइन 1-800-273-8255 पर या वंद्रेवाला फ़ाउंडेशन हेल्पलाइन 1-860-266-2345 पर या आसरा +91-22-2754-6669 पर तुरंत कॉल करें .",
          "Other": "अन्य",
          "Add": "जोड़ें",
          "Need support on": "पर समर्थन चाहिए",
          "Give us a rough idea of the issues that you deal with on a daily basis. You may select more than one.":
              "हमें उन मुद्दों का एक मोटा विचार दें जिनसे आप दैनिक आधार पर निपटते हैं। आप एक से अधिक का चयन कर सकते हैं।",
          "Searching for a counceller": "काउंसलर की तलाश की जा रही है",
          "Get Started": "शुरू करें",
          "Depression": "डिप्रेशन",
          "Addiction": "लत",
          "More": "अधिक",
          "Videos": "वीडियोस",
          "Discover previously unknown features by learning more about Solh Features":
              "Solh के अन्य सुविधाओं के बारे में जानें",
          "Create Journal": "जर्नल बनाएं",
          "Post": "पोस्ट करें",
          "Feelings": "भावनाएँ",
          "Add Image/Video": "इमेज/वीडियो लगाएं  ",
          "Choose your type": "अपना प्रकार चुनें",
          "Delete Feeling": "भावना मिटाए",
          "Are you sure you want to delete this feeling?":
              "क्या आप वाकई इस भावना को मिटाना चाहते हैं?",
          "Tag": "टैग",
          "Select People": "लोगों का चयन करें",
          "Oops! No connection found.": "Oops! कोई संबंध नहीं मिला",
          "Select Group": "ग्रुप चुनें",
          "Anonymous Profile": "गुमनाम प्रोफाइल",
          "Anonymous profile": "गुमनाम प्रोफाइल",
          "Name, Avatar": "नाम, अवतार",
          "Post or leave a comment, join group, book appointment, etc anonymously.":
              " गुमनाम रूप से टिप्पणी या पोस्ट करें, ग्रुप में शामिल हो या अपॉइंटमेंट बुक करें",
          "Username Already taken": "यूजरनेम पहले ही लिया जा चुका हैं",
          "No Journals": "जर्नल्स नहीं है",
          "No Post": "कोई पोस्ट नहीं है",
          "Solh": "Solh",
          "Discover": "खोजें",
          "Click to reload": "दोबारा लोड करने के लिए क्लिक करें",
          "Hi, there": "नमस्ते",
          "Volunteer": "वॉलंटियर",
          "Counsellor": "काउंसलर",
          "Video Trimmer": "वीडियो ट्रिमर",
          "What's on your mind?": "आपके दिमाग में क्या है",
          "post in group": "ग्रुप में पोस्ट करें",
          "Anxiety, Corporate Stress, Family Issues":
              "चिंता, कॉर्पोरेट तनाव, पारिवारिक मामले",
          "Leading Solh Experts": "प्रमुख Sohl एक्सपर्ट्स",
          "Coming Soon": "जल्द आ रहा है",
          "Delete this comment": "इस टिप्पणी को हटाएं",
          "Select for best comment": "सर्वश्रेष्ठ टिप्पणी के लिए चुनें",
          "Goals": "लक्ष्य",
          "Post Liked By": "द्वारा पसंद की गई पोस्ट",
          "Delete this post": "इस पोस्ट को हटाएं",
          "Report this post": "इस पोस्ट को रिपोर्ट करें",
          "Latest Reads": "लेटेस्ट रीड्स",
          "Terms of Use": "उपयोग की शर्तें",
          "Give Feedback": "प्रतिक्रिया दें",
          "Know Us More": "हमें और अधिक जानें",
          "Contact Us": "हमसे संपर्क करें",
          "Privacy Policy": "निजता नीति",
          "Don't show this post again": "इस पोस्ट को दोबारा ना दिखाएं",
          "Post Successfully Removed From Your Feed":
              "पोस्ट को आपकी फ़ीड से सफलतापूर्वक हटा दिया गया है",
          "We are sorry for your inconvenience due to this post/person. Please let us know what is the problem with this post/person":
              "इस पोस्ट/व्यक्ति के कारण आपको हुई असुविधा के लिए हमें खेद है। कृपया हमें बताएं कि इस पोस्ट/व्यक्ति के साथ क्या समस्या है?",
          "Report": "रिपोर्ट",
          "Successfully Reported": "सफलतापूर्वक रिपोर्ट किया गया",
          "Mood Analytics": "मूड एनालिटिक्स",
          "Tap to add current mood": "वर्तमान मूड जोड़ने के लिए टैप करें",
          "Mood count": "मूड काउंट",
          "Week": "सप्ताह",
          "30 days": "30 दिन",
          "60 days": "60 दिन ",
          "No mood found": "कोई मूड नहीं मिला",
          "Average Mood": "एवरेज मूड",
          "Loading ...": "लोड हो रहा है...",
          "Express Yourself": "अपने आप को व्यक्त करें",
          "Done": "हो गया",
          "Why are you feeling like this ?": "आप ऐसा क्यों महसूस कर रहे हैं",
          "Select/Add Goal": "लक्ष्य जोड़ें/चुनें",
          "Custom Goals": "अपनी पसदं के लक्ष्य बनाएं ",
          "No Goals Found": "कोई लक्ष्य नहीं मिला ",
          "Add Goals": "लक्ष्य जोड़ें",
          "Quite Smoking": "धूम्रपान छोड़ें",
          "Take nicotine, Do exercise": "निकोटीन लें, व्यायाम करें",
          "You will be achiveing this goal by doing following :-":
              "आप निम्न कार्य करके इस लक्ष्य को प्राप्त करेंगे:-",
          "Occurance": "घटना",
          "Once": "एक बार",
          "Daily": "प्रतिदिन",
          "Please enter goal name": "कृपया लक्ष्य का नाम डालें",
          "Please select task": "कृपया कार्य चुनें",
          "You can achieve the goal by using the recommended activities":
              "आप सुझाई गई गतिविधियों का उपयोग करके लक्ष्य प्राप्त कर सकते हैं",
          "occurrence": "घटित होना",
          "Add Task +": "कार्य जोड़ें",
          "Max Reminder": "अधिकतम याद दिलाने वाला",
          "my Goals": "मेरे लक्ष्य",
          "My Goals": "मेरे लक्ष्य",
          "Settings": "सेटिंग्स",
          "Is activity completed ?": "क्या गतिविधि पूरी हो गई है?",
          "Not yet": "अभी नहीं",
          "Do you sure you want to delete this goal ?":
              "क्या आप वाकई इस लक्ष्य को हटाना चाहते हैं?",
          "Select Category": "श्रेणी चुनें",
          "Logout": "लॉग आउट",
          "LOG IN / SIGN UP": "लॉग इन/साइन अप",
          "Appointments": "अपॉइंटमेंट",
          "Scheduled": "अनुसूचित",
          "Counselling": "परामर्श",
          "Allied": "अलाइड",
          "Owners name": "मालिक का नाम",
          "Services are in process and we'll be delivering them soon. Please keep an eye on your emails.":
              "सेवाएं प्रक्रिया में हैं और हम उन्हें जल्द ही डिलीवर कर देंगे। कृपया अपने ईमेल पर नजर रखें।",
          "Duration": "अवधि",
          "Blocked Users": "ब्लॉक्ड यूजर",
          "Users you've blocked are listed below; tap any of them to unblock them.":
              "आपके द्वारा ब्लॉक किए गए यूजर नीचे सूचीबद्ध हैं; उन्हें अनब्लॉक करने के लिए उनमें से किसी पर टैप करें।",
          "Unblock": "अनब्लॉक",
          "Connection": "सम्बन्ध",
          "Languages": "भाषा",
          "sent": "भेज दिया",
          "See Profile": "प्रोफाइल देखें",
          "received": "प्राप्त हुआ",
          "Decline": "अस्वीकार",
          "All": "सभी",
          "Recent": "हाल का",
          "Invites": "आमंत्रण",
          "Waiting": "प्रतीक्षा कर रहा है",
          "Disclaimer": "डिस्क्लेमर",
          "Please accept connection requests of known persons only":
              "कृपया केवल ज्ञात व्यक्तियों के कनेक्शन अनुरोध स्वीकार करें",
          "Likes": "लाइक्स",
          "Connections": "सम्बन्ध",
          "You are almost there": "आप लगभग वहाँ हैं",
          "Let's take your profile from good to great. The details matter":
              "चलिए आपकी प्रोफ़ाइल को अच्छे से बढ़िया बनाते हैं। विवरण मायने रखता है",
          "Edit Profile": "एडिट प्रोफाइल",
          "User Type": "यूजर टाइप",
          "Save chanages": "परिवर्तनों को सुरक्षित करें",
          "Add an avatar": "अवतार जोड़ें",
          "Upload a picture or choose one from our library of images that describes you best.":
              "अपनी एक तस्वीर अपलोड करें या हमारी लाइब्रेरी में से एक इमेज चुनें जो आपका सबसे अच्छा वर्णन करती है",
          "We need your email for safekeeping your account. We promise to not spam you.":
              "आपके अकाउंट को सुरक्षित रखने के लिए हमें आपके ईमेल की आवश्यकता है। हम आपको स्पैम नहीं करने का वादा करते हैं",
          "Anonymous Profile": "गुमनाम प्रोफाइल",
          "Post or leave a comment, join group, book appointment, etc anonymously.":
              "गुमनाम रूप से टिप्पणी या पोस्ट करें, ग्रुप में शामिल हो या अपॉइंटमेंट बुक करें",
          "Anonymous Name": "अज्ञात नाम",
          "Something about you...": "आप के बारे में कुछ...",
          "Tell something about you": "अपने बारे में कुछ बताएं",
          "Bio": "बायो",
          "write here": "यहाँ लिखें",
          "Emergency Contact": "आपातकालीन संपर्क",
          "It is always good to have someone on speed dial isn't it?":
              "स्पीड डायल पर किसी का होना हमेशा अच्छा होता है, है ना?",
          "Select Connection": "सम्बन्ध चुनें",
          "Select": "चुनें",
          "SOS Message": "SOS मैसेज",
          "Part of an organisation ?": "क्या आप किसी संगठन का हिस्सा है?",
          "Please provide details below if you are boarding as part of an organization.":
              "यदि आप किसी संगठन के हिस्से के रूप में बोर्डिंग कर रहे हैं तो कृपया नीचे विवरण प्रदान करें।",
          "Organisation Type": "संगठन प्रकार?",
          "Educational Institutions": "शैक्षिक संस्थान",
          "Corporate": "कॉर्पोरेट",
          "Others": "अन्य",
          "Whats your gender ?": "आपका लिंग क्या है",
          "If you don't confirm to any of the options below, don't worry. We've got space for everybody":
              "यदि आप नीचे दिए गए किसी भी विकल्प की पुष्टि नहीं करते हैं, तो चिंता न करें। हमारे पास सबके लिए जगह है",
          "Male": "पुरुष",
          "Female": "स्त्री",
          "Posts": "पोस्ट",
          "Edit Anonymous Profile": "गुमनाम प्रोफइल को एडिट करें",
          "Reload Profile": "प्रोफाइल रीलोड करें",
          "Personal Details": "व्यक्तिगत विवरण",
          "Gender": "लिंग",
          "DOB": "जन्मतिथि",
          "Select country": "अपना देश चुनें",
          "Save Changes": "परिवर्तनों को सुरक्षित करें",
          "Account Privacy": "अकाउंट गोपनीयता",
          "Delete Account": "अकाउंट हटाएं",
          "Today's Goals": "आज के लक्ष्य",
          "Track your today's goals": "अपने आज के लक्ष्यों को ट्रैक करें",
          "Account & Privacy": "अकाउंट और गोपनीयता",
          "Delete account": "खाता हटाएं",
          "Created": "बनाया गया",
          "Diary Entries": "डायरी एंट्रीज",
          "No groups created yet": "अभी तक कोई समूह नहीं बनाया गया है",
          "Now": "अभी",
          "Psychological Tests": "मनोवैज्ञानिक परीक्षण",
          "Our Psychology Tests help you understand whether certain mental health or emotional issues may be of concern to you.":
              "हमारे मनोविज्ञान परीक्षण आपको यह समझने में मदद करते हैं कि कुछ मानसिक स्वास्थ्य या भावनात्मक मुद्दे आपके लिए चिंता का विषय हो सकते हैं या नहीं।",
          "Discover Test": "खोज परीक्षण",
          "Result History": "परिणाम इतिहास",
          "Video Playlist": "वीडियो प्लेलिस्ट",
          "Discover previously unknown features by learning more about Solh Features":
              "Solh सुविधाओं के बारे में अधिक जानकारी प्राप्त करके पहले अज्ञात सुविधाओं की खोज करें",
          "Publically": "सार्वजनिक",
          "Groups": "समूह",
          "Add Image/Video": "इमेज/वीडियो जोड़ें",
          "Sample Goals": "लक्ष्यों के सैंपल",
          "Set Goal": "लक्ष्य तय करें",
          "Your First Name": "आपका प्रथम नाम",
          "Your Last Name": "आपका अंतिम नाम",
          "About/Bio": "विषय",
          "Your Email id": "आपकी इ-मेल",
          "Ratings": "मूल्यांकन",
          "Select Day": "दिन का चयन करें",
          "Select Time": "समय का चयन करें",
          "Book Anonymously": "गुमनाम रूप से बुक करें",
          "Email-Id": "ई-मेल",
          "Mobile no": "मोबाइल नंबर",
          "Mobile No.": "मोबाइल नंबर",
          "How Can we help ? (optional)":
              "हम आपकी कैसे सहायता कर सकते है?(वैकल्पिक)",
          "Preffered Date & Time": "पसंदीदा तिथि और समय",
          "Clear your Mind. Find Happiness in Chaos. Seek Solh Within.":
              "अपना दिमाग साफ़ करें। अराजकता में खुशी खोजें। अपने भीतर SOLH तलाशें। ",
          "Already have an account?":
              "क्या आपका पास पहले से ही एक अकाउंट मौजूद है?",
          "Verify Phone No.": "फ़ोन नंबर की पुष्टि करें",
          "Please enter the 6 digit code sent to ":
              "कृपया भेजा गया 6 अंकों का कोड दर्ज करें",
          "Didn't recieve a code? ": "कोड प्राप्त नहीं हुआ?",
          "What should we call you?": "हम आपको क्या कहकर बुलाएं?",
          "It helps us to know your real name, don't worry we won't share it with anyone without your permission.":
              "यह हमें आपका वास्तविक नाम जानने में मदद करता है, चिंता न करें हम आपकी अनुमति के बिना इसे किसी के साथ साझा नहीं करेंगे।",
          "When is your birthday ?": "आपका जन्मदिन कब है ?",
          "We want to know how many years of experience you have dealing with life :) ":
              "हम जानना चाहते हैं कि आपको जीवन से निपटने का कितने वर्षों का अनुभव है :)",
          "Are you sure ? Deleting your account will  delete all your posts, appointments, journals, likes & comments & all other engagements.":
              "क्या आप सुनिश्चित हैं ? आपके अकाउंट को हटाने से आपकी सभी पोस्ट, अपॉइंटमेंट, पत्रिकाएं, पसंद, टिप्पणियां और अन्य सभी कार्य हटा दिए जाएंगे।",
          "Notification": "अधिसूचना",
          "Upload a pciture or choose one from our library of images that describes you best.":
              "एक तस्वीर अपलोड करें या हमारी लाइब्रेरी में से एक इमेज चुनें जो आपका सबसे अच्छा वर्णन करती है।",
          "Email": "ईमेल",
          "your email-id": "आपकी ई-मेल ID",
          "Enter Custom issue": "कस्टम मुद्दा दर्ज करें",
          "No Completed Appointment yet":
              "अभी तक कोई अपॉइंटमेंट पूरा नहीं हुआ है",
          "Deleting your account will  delete all your posts, appointments, journals, likes & comments & all other engagements. You will have to create a new account and start your journey from the beginning if you wish to return.":
              "आपके अकाउंट को हटाने से आपकी सभी पोस्ट, अपॉइंटमेंट, पत्रिकाएं, पसंद और टिप्पणियां और अन्य सभी कार्य हटा दिए जाएंगे। यदि आप वापस लौटना चाहते हैं तो आपको एक नया अकाउंट बनाना होगा और दोबारा शुरुआत करनी होगी।"
        },
        "en_us": en_us_map,
      };
}

Map<String, String> en_us_map = {
  "Do you really want to exit app?": "Do you really want to exit app?",
  "Yes": "Yes",
  "No": "No",
  "ERROR": "ERROR",
  "TRY AGAIN": "TRY AGAIN",
  "Not found": "Not found",
  "Find help": "Find help",
  "Reject": "Reject",
  "Trending Posts": "Trending Posts",
  "Accept": "Accept",
  "Other Detail": "Other Detail",
  "My Diary": "My Diary",
  "Post Publically": "Post Publically",
  "Close": "Close",
  "Diary Entries": "Diary Entries",
  "Issues, Organisation": "Issues, Organisation",
  "Well, there's nothing here! Why don't you begin today?":
      "Well, there's nothing here! Why don't you begin today?",
  "Psychological Capital": "Psychological Capital",
  "Your Capital": "Your Capital",
  "Your Psychological Capital": "Your Psychological Capital",
  "This is the grand total of psychological Capital based on your Engagement on the app      ":
      "This is the grand total of psychological Capital based on your Engagement on the app      ",
  "Badges up Next": "Badges up Next",
  "Earn more psychological capital for respective badge & make it yours":
      "Earn more psychological capital for respective badge & make it yours",
  "Typing....": "Typing....",
  "Please wait a moment while we connect you to one of our Solh certified professionals.":
      "Please wait a moment while we connect you to one of our Solh certified professionals.",
  "Please take this conversation further. The seeker is waiting for you.":
      "Please take this conversation further. The seeker is waiting for you.",
  "Rate your Experience": "Rate your Experience",
  "Your chat ended, Please rate your experience":
      "Your chat ended, Please rate your experience",
  "Skip": "Skip",
  "Please write your feedback here": "Please write your feedback here",
  "Submit": "Submit",
  "Groups For You": "Groups For You",
  "Do you really want to end the chat?": "Do you really want to end the chat?",
  "Cancel": "Cancel",
  "Leave": "Leave",
  "Comments": "Comments",
  "You can not see this user": "You can not see this user",
  "Best": "Best",
  "My Profile": "My Profile",
  "Replies": "Replies",
  "Likes": "Likes",
  "Feeling": "Feeling",
  "Go To Group": "Go To Group",
  "join": "join",
  "Connect": "Connect",
  "Connections": "Connections",
  "Message": "Message",
  "Connect": "Connect",
  "Posts": "Posts",
  "Capital": "Capital",
  "Unfriend": "Unfriend",
  "Cancle": "Cancle",
  "Sessions & Packages": "Sessions & Packages",
  "Report this person": "Report this person",
  "Wheel of Emotions": "Wheel of Emotions",
  "Activity Log": "Activity Log",
  "Block this person": "Block this person",
  "Person Successfully Blocked": "Person Successfully Blocked",
  "Oops !! Something Went Wrong": "Oops !! Something Went Wrong",
  "Successfully Reported User": "Successfully Reported User",
  "Online": "Online",
  "Offline": "Offline",
  "Completed": "Completed",
  "No Scheduled Appointment yet": "No Scheduled Appointment yet",
  "Session": "Session",
  "Not Available Now": "Not Available Now",
  "Booking Online Session": "Booking Online Session",
  "Confirm": "Confirm",
  "Thank You": "Thank You",
  "Your appointment has been successfully booked on":
      "Your appointment has been successfully booked on",
  "No Package": "No Package",
  "Total Payable": "Total Payable",
  "Buy Plan": "Buy Plan",
  "Continue": "Continue",
  "Years": "Years",
  "About": "About",
  "Select Pack": "Select Pack",
  "Hide": "Hide",
  "View": "View",
  "Tax Incl.": "Tax Incl.",
  "Change": "Change",
  "Book Now & Pay Later": "Book Now & Pay Later",
  "Billing Details": "Billing Details",
  "Consultaion Fee": "Consultaion Fee",
  "By confirming you agree": "By confirming you agree",
  "Terms & Conditions": "Terms & Conditions",
  "Solh Promises": "Solh Promises",
  "Complete anonymity": "Complete anonymity",
  "A safe space with no judgement": "A safe space with no judgement",
  "The best doctors and therapists": "The best doctors and therapists",
  "Round the clock support": "Round the clock support",
  "Details": "Details",
  "Paid": "Paid",
  "Consultation Fee": "Consultation Fee",
  "Book Appointment": "Book Appointment",
  "Starting @": "Starting @",
  "Show More": "Show More",
  "Show less": "Show less",
  "No Consultant available for your country":
      "No Consultant available for your country",
  "No Doctors Found": "No Doctors Found",
  "View All": "View All",
  "Request Sent": "Request Sent",
  "Email-id": "Email-id",
  "Benefits": "Benefits",
  "No results found": "No results found",
  "Filter counsellors": "Filter counsellors",
  "Country": "Country",
  "Clinician": "Clinician",
  "Allied Therapy": "Allied Therapy",
  "years": "years",
  "Preview": "Preview",
  "Consultants": "Consultants",
  "Name, age, gender": "Name, age, gender",
  "Issues": "Issues",
  "Speciality": "Speciality",
  "Clear all": "Clear all",
  "Apply": "Apply",
  "Allied Therapies": "Allied Therapies",
  "Featured Therapists": "Featured Therapists",
  "Therepist Name": "Therepist Name",
  "Profession": "Profession",
  "Consultations": "Consultations",
  "Rating": "Rating",
  "Recorded": "Recorded",
  "Live packages": "Live packages",
  "Popular Packages": "Popular Packages",
  "Solh Mates": "Solh Mates",
  "Today": "Today",
  "Search for Support": "Search for Support",
  "Search by Profession": "Search by Profession",
  "Search for People, consultants, Posts or groups ...":
      "Search for People, consultants, Posts or groups ...",
  "No Result Found": "No Result Found",
  "Edit Group Details": "Edit Group Details",
  "Create Group": "Create Group",
  "Public": "Public",
  "Save": "Save",
  "Next": "Next",
  "posts": "posts",
  "Group Description": "Group Description",
  "Join Group": "Join Group",
  "Post in group": "Post in group",
  "See Post": "See Post",
  "Members": "Members",
  "Admin": "Admin",
  "Edit": "Edit",
  "Delete": "Delete",
  "Exit group": "Exit group",
  "Do You want to Exit group ?": "Do You want to Exit group ?",
  "Yes": "Yes",
  "Join As": "Join As",
  "Join": "Join",
  "Invite Members": "Invite Members",
  "Send Invite": "Send Invite",
  "Groups": "Groups",
  "Home": "Home",
  "Joined": "Joined",
  "No groups joined yet": "No groups joined yet",
  "new suggestions are on the way": "new suggestions are on the way",
  "Blog Details": "Blog Details",
  "Journaling": "Journaling",
  "Goal Setting": "Goal Setting",
  "Add Goals +": "Add Goals +",
  "I want to work on": "I want to work on",
  "Self Assessments": "Self Assessments",
  "Get Help": "Get Help",
  "Take the first step": "Take the first step",
  "Anonymous": "Anonymous",
  "Anxiety": "Anxiety",
  "Overwhelmed with emotions: Talk to a Solh counsellor NOW":
      "Overwhelmed with emotions: Talk to a Solh counsellor NOW",
  "Start chatting for free right away, with a Solh Counselor.":
      "Start chatting for free right away, with a Solh Counselor.",
  "Allied Experts": "Allied Experts",
  "You will be connected to solh counsellor":
      "You will be connected to solh counsellor",
  "Talk Now": "Talk Now",
  "DISCLAMER": "DISCLAMER",
  "We are not a medical emergency or suicide prevention service . If you are feeling suicidal Helpline at 1-860-266-2345 or Aasra at +91-22-2754-6669 immediately.":
      "We are not a medical emergency or suicide prevention service . If you are feeling suicidal, please call a helpline such as the National Suicide Prevention Lifeline at 1-800-273-8255 or the Vandrevala Foundation Helpline at 1-860-266-2345 or Aasra at +91-22-2754-6669 immediately.",
  "Other": "Other",
  "Add": "Add",
  "Need support on": "Need support on",
  "Give us a rough idea of the issues that you deal with on a daily basis. You may select more than one.":
      "Give us a rough idea of the issues that you deal with on a daily basis. You may select more than one.",
  "Searching for a counceller": "Searching for a counceller",
  "Get Started": "Get Started",
  "Depression": "Depression",
  "Addiction": "Addiction",
  "More": "More",
  "Videos": "Videos",
  "Discover previously unknown features by learning more about Solh Features":
      "Discover previously unknown features by learning more about Solh Features",
  "Create Journal": "Create Journal",
  "Post": "Post",
  "Feelings": "Feelings",
  "Add Image/Video": "Add Image/Video",
  "Choose your type": "Choose your type",
  "Delete Feeling": "Delete Feeling",
  "Are you sure you want to delete this feeling?":
      "Are you sure you want to delete this feeling?",
  "Tag": "Tag",
  "Select People": "Select People",
  "Oops! No connection found.": "Oops! No connection found.",
  "Select Group": "Select Group",
  "Anonymous Profile": "Anonymous Profile",
  "Anonymous profile": "Anonymous profile",
  "Name, Avatar": "Name, Avatar",
  "Post or leave a comment, join group, book appointment, etc anonymously.":
      "Post or leave a comment, join group, book appointment, etc anonymously.",
  "Username Already taken": "Username Already taken",
  "No Journals": "No Journals",
  "No Post": "No Post",
  "Solh": "Solh",
  "Discover": "Discover",
  "Click to reload": "Click to reload",
  "Hi, there": "Hi, there",
  "Volunteer": "Volunteer",
  "Counsellor": "Counsellor",
  "Video Trimmer": "Video Trimmer",
  "What's on your mind?": "What's on your mind?",
  "post in group": "post in group",
  "Anxiety, Corporate Stress, Family Issues":
      "Anxiety, Corporate Stress, Family Issues",
  "Leading Solh Experts": "Leading Solh Experts",
  "Coming Soon": "Coming Soon",
  "Delete this comment": "Delete this comment",
  "Select for best comment": "Select for best comment",
  "Goals": "Goals",
  "Post Liked By": "Post Liked By",
  "Delete this post": "Delete this post",
  "Report this post": "Report this post",
  "Latest Reads": "Latest Reads",
  "Terms of Use": "Terms of Use",
  "Give Feedback": "Give Feedback",
  "Know Us More": "Know Us More",
  "Contact Us": "Contact Us",
  "Privacy Policy": "Privacy Policy",
  "Don't show this post again": "Don't show this post again",
  "Post Successfully Removed From Your Feed":
      "Post Successfully Removed From Your Feed",
  "We are sorry for your inconvenience due to this post/person. Please let us know what is the problem with this post/person":
      "We are sorry for your inconvenience due to this post/person. Please let us know what is the problem with this post/person",
  "Report": "Report",
  "Successfully Reported": "Successfully Reported",
  "Mood Analytics": "Mood Analytics",
  "Tap to add current mood": "Tap to add current mood",
  "Mood count": "Mood count",
  "Week": "Week",
  "30 days": "30 days",
  "60 days": "60 days",
  "No mood found": "No mood found",
  "Average Mood": "Average Mood",
  "Loading ...": "Loading ...",
  "Express Yourself": "Express Yourself",
  "Done": "Done",
  "Why are you feeling like this ?": "Why are you feeling like this ?",
  "Select/Add Goal": "Select/Add Goal",
  "Custom Goals": "Custom Goals",
  "No Goals Found": "No Goals Found",
  "Add Goals": "Add Goals",
  "Quite Smoking": "Quite Smoking",
  "Take nicotine, Do exercise": "Take nicotine, Do exercise",
  "You will be achiveing this goal by doing following :-":
      "You will be achiveing this goal by doing following :-",
  "Occurance": "Occurance",
  "Once": "Once",
  "Daily": "Daily",
  "Please enter goal name": "Please enter goal name",
  "Please select task": "Please select task",
  "You can achieve the goal by using the recommended activities":
      "You can achieve the goal by using the recommended activities",
  "occurrence": "occurrence",
  "Add Task +": "Add Task +",
  "Max Reminder": "Max Reminder",
  "Goals": "Goals",
  "Add": "Add",
  "my Goals": "my Goals",
  "My Goals": "My Goals",
  "Settings": "Settings",
  "Is activity completed ?": "Is activity completed ?",
  "Not yet": "Not yet",
  "Do you sure you want to delete this goal ?":
      "Do you sure you want to delete this goal ?",
  "Select Category": "Select Category",
  "Logout": "Logout",
  "LOG IN / SIGN UP": "LOG IN / SIGN UP",
  "Appointments": "Appointments",
  "Scheduled": "Scheduled",
  "Counselling": "Counselling",
  "Allied": "Allied",
  "Owners name": "Owners name",
  "Services are in process and we'll be delivering them soon. Please keep an eye on your emails.":
      "Services are in process and we'll be delivering them soon. Please keep an eye on your emails.",
  "Duration": "Duration",
  "Blocked Users": "Blocked Users",
  "Users you've blocked are listed below; tap any of them to unblock them.":
      "Users you've blocked are listed below; tap any of them to unblock them.",
  "Unblock": "Unblock",
  "Connection": "Connection",
  "Languages": "Languages",
  "sent": "sent",
  "See Profile": "See Profile",
  "received": "received",
  "Decline": "Decline",
  "All": "All",
  "Recent": "Recent",
  "Invites": "Invites",
  "Waiting": "Waiting",
  "Disclaimer": "Disclaimer",
  "Please accept connection requests of known persons only":
      "Please accept connection requests of known persons only",
  "Likes": "Likes",
  "Connections": "Connections",
  "You are almost there": "You are almost there",
  "Let's take your profile from good to great. The details matter":
      "Let's take your profile from good to great. The details matter",
  "Edit Profile": "Edit Profile",
  "User Type": "User Type",
  "Save chanages": "Save chanages",
  "Add an avatar": "Add an avatar",
  "Upload a picture or choose one from our library of images that describes you best.":
      "Upload a picture or choose one from our library of images that describes you best.",
  "We need your email for safekeeping your account. We promise to not spam you.":
      "We need your email for safekeeping your account. We promise to not spam you.",
  "Anonymous Profile": "Anonymous Profile",
  "Post or leave a comment, join group, book appointment, etc anonymously.":
      "Post or leave a comment, join group, book appointment, etc anonymously.",
  "Anonymous Name": "Anonymous Name",
  "Something about you...": "Something about you...",
  "Tell something about you": "Tell something about you",
  "Bio": "Bio",
  "write here": "write here",
  "Emergency Contact": "Emergency Contact",
  "It is always good to have someone on speed dial isn't it?":
      "It is always good to have someone on speed dial isn't it?",
  "Select Connection": "Select Connection",
  "Select": "Select",
  "SOS Message": "SOS Message",
  "Part of an organisation ?": "Part of an organisation ?",
  "Please provide details below if you are boarding as part of an organization.":
      "Please provide details below if you are boarding as part of an organization.",
  "Organisation Type": "Organisation Type",
  "Educational Institutions": "Educational Institutions",
  "Corporate": "Corporate",
  "Others": "Others",
  "Whats your gender ?": "Whats your gender ?",
  "सेवाएं प्रक्रिया में हैं और हम उन्हें जल्द ही डिलीवर कर देंगे। कृपया अपने ईमेल पर नजर रखें।":
      "सेवाएं प्रक्रिया में हैं और हम उन्हें जल्द ही डिलीवर कर देंगे। कृपया अपने ईमेल पर नजर रखें।",
  "Male": "Male",
  "Female": "Female",
  "Posts": "Posts",
  "Edit Anonymous Profile": "Edit Anonymous Profile",
  "Reload Profile": "Reload Profile",
  "Personal Details": "Personal Details",
  "Gender": "Gender",
  "DOB": "DOB",
  "Select country": "Select country",
  "Save Changes": "Save Changes",
  "Account Privacy": "Account Privacy",
  "Delete Account": "Delete Account",
  "Today's Goals": "Today's Goals",
  "Track your today's goals": "Track your today's goals",
  "Account & Privacy": "Account & Privacy",
  "Delete account": "Delete account",
  "Created": "Created",
  "Diary Entries": "Diary Entries",
  "No groups created yet": "No groups created yet",
  "Now": "Now",
  "Psychological Tests": "Psychological Tests",
  "Our Psychology Tests help you understand whether certain mental health or emotional issues may be of concern to you.":
      "Our Psychology Tests help you understand whether certain mental health or emotional issues may be of concern to you.",
  "Discover Test": "Discover Test",
  "Result History": "Result History",
  "Video Playlist": "Video Playlist",
  "Discover previously unknown features by learning more about Solh Features":
      "Discover previously unknown features by learning more about Solh Features",
  "Publically": "Publically",
  "Groups": "Groups",
  "Add Image/Video": "Add Image/Video",
  "Sample Goals": "Sample Goals",
  "Set Goal": "Set Goal",
  "Your First Name": "Your First Name",
  "Your Last Name": "Your Last Name",
  "About/Bio": "About/Bio",
  "Your Email id": "Your Email id",
  "Ratings": "Ratings",
  "Select Day": "Select Day",
  "Select Time": "Select Time",
  "Book Anonymously": "Book Anonymously",
  "Email-Id": "Email-Id",
  "Mobile no": "Mobile no",
  "How Can we help ? (optional)": "How Can we help ? (optional)",
  "Preffered Date & Time": "Preffered Date & Time",
  "Deleting your account will  delete all your posts, appointments, journals, likes & comments & all other engagements. You will have to create a new account and start your journey from the beginning if you wish to return.":
      "Deleting your account will  delete all your posts, appointments, journals, likes & comments & all other engagements. You will have to create a new account and start your journey from the beginning if you wish to return."
};
